-- 创建评论表
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  parent_id BIGINT DEFAULT 0 REFERENCES comments(id),
  game_id VARCHAR(100) NOT NULL DEFAULT 'steal-brainrot',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('approved', 'pending', 'spam', 'trash')),
  ip_address INET,
  like_count INTEGER DEFAULT 0,
  dislike_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX idx_comments_game_id ON comments(game_id);
CREATE INDEX idx_comments_parent_id ON comments(parent_id);
CREATE INDEX idx_comments_status ON comments(status);
CREATE INDEX idx_comments_created_at ON comments(created_at);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_comments_updated_at
    BEFORE UPDATE ON comments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- RLS (Row Level Security) 策略
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 允许所有用户读取已批准的评论
CREATE POLICY "Anyone can view approved comments" ON comments
    FOR SELECT USING (status = 'approved');

-- 允许所有用户插入评论（需要审核）
CREATE POLICY "Anyone can insert comments" ON comments
    FOR INSERT WITH CHECK (true);

-- 只允许认证用户更新自己的评论（可选）
CREATE POLICY "Users can update own comments" ON comments
    FOR UPDATE USING (auth.uid()::text = email);

-- 创建评论投票表（可选）
CREATE TABLE comment_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  ip_address INET NOT NULL,
  vote_type VARCHAR(10) NOT NULL CHECK (vote_type IN ('like', 'dislike')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(comment_id, ip_address)
);

-- 为投票表创建索引
CREATE INDEX idx_comment_votes_comment_id ON comment_votes(comment_id);
CREATE INDEX idx_comment_votes_ip_address ON comment_votes(ip_address);

-- RLS for comment_votes
ALTER TABLE comment_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view comment votes" ON comment_votes FOR SELECT USING (true);
CREATE POLICY "Anyone can insert comment votes" ON comment_votes FOR INSERT WITH CHECK (true);