-- =====================================================
-- 一定要在 Supabase Dashboard 中执行这个 SQL
-- =====================================================

-- 1. 创建评论表
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  parent_id BIGINT DEFAULT 0 REFERENCES comments(id),
  game_id VARCHAR(100) NOT NULL DEFAULT 'steal-brainrot',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('approved', 'pending', 'spam', 'trash')),
  ip_address INET,
  user_agent TEXT,
  like_count INTEGER DEFAULT 0,
  dislike_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 创建索引
CREATE INDEX IF NOT EXISTS idx_comments_game_id ON comments(game_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at);

-- 3. 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_comments_updated_at ON comments;
CREATE TRIGGER update_comments_updated_at
    BEFORE UPDATE ON comments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 4. 启用 RLS
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 5. 删除已存在的策略
DROP POLICY IF EXISTS "Anyone can view approved comments" ON comments;
DROP POLICY IF EXISTS "Anyone can insert comments" ON comments;
DROP POLICY IF EXISTS "Users can update own comments" ON comments;

-- 6. 创建 RLS 策略
CREATE POLICY "Anyone can view approved comments" ON comments
    FOR SELECT USING (status = 'approved');

CREATE POLICY "Anyone can insert comments" ON comments
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update own comments" ON comments
    FOR UPDATE USING (auth.uid()::text = email);

-- 7. 创建评论投票表
CREATE TABLE IF NOT EXISTS comment_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  ip_address INET NOT NULL,
  vote_type VARCHAR(10) NOT NULL CHECK (vote_type IN ('like', 'dislike')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(comment_id, ip_address)
);

-- 8. 为投票表创建索引
CREATE INDEX IF NOT EXISTS idx_comment_votes_comment_id ON comment_votes(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_votes_ip_address ON comment_votes(ip_address);

-- 9. RLS for comment_votes
ALTER TABLE comment_votes ENABLE ROW LEVEL SECURITY;

-- 10. 删除已存在的投票策略
DROP POLICY IF EXISTS "Anyone can view comment votes" ON comment_votes;
DROP POLICY IF EXISTS "Anyone can insert comment votes" ON comment_votes;

-- 11. 创建投票表策略
CREATE POLICY "Anyone can view comment votes" ON comment_votes FOR SELECT USING (true);
CREATE POLICY "Anyone can insert comment votes" ON comment_votes FOR INSERT WITH CHECK (true);

-- 12. 验证表创建成功
SELECT 'comments table created successfully' as status;
SELECT 'comment_votes table created successfully' as status;

-- 13. 插入一条测试评论
INSERT INTO comments (author, email, content, game_id, status, ip_address)
VALUES ('系统测试', 'system@test.com', '表创建后的测试评论', 'steal-brainrot', 'approved', '127.0.0.1')
RETURNING id, author, created_at;