import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://ptukqwqbpjzqpqzvlrle.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dWtxd3FicGp6cXBxenZscmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4Mjk3MDksImV4cCI6MjA3ODQwNTcwOX0.PH0-iJiSg7NVgTtNaLzpGisRGgR8iDcRHINI6q0EK7Q'

const supabase = createClient(supabaseUrl, supabaseAnonKey)

// SQL 语句
const createTablesSQL = `
-- 创建评论表
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  parent_id BIGINT DEFAULT 0 REFERENCES comments(id),
  game_id VARCHAR(100) NOT NULL DEFAULT 'steal-brainrot',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('approved', 'pending', 'spam', 'trash')),
  ip_address INET,
  user_agent TEXT,
  like_count INTEGER DEFAULT 0,
  dislike_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_comments_game_id ON comments(game_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at);

-- 创建更新时间触发器函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 创建触发器
DROP TRIGGER IF EXISTS update_comments_updated_at ON comments;
CREATE TRIGGER update_comments_updated_at
    BEFORE UPDATE ON comments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 启用 RLS
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略
DROP POLICY IF EXISTS "Anyone can view approved comments" ON comments;
DROP POLICY IF EXISTS "Anyone can insert comments" ON comments;
DROP POLICY IF EXISTS "Users can update own comments" ON comments;

-- 创建新的 RLS 策略
CREATE POLICY "Anyone can view approved comments" ON comments
    FOR SELECT USING (status = 'approved');

CREATE POLICY "Anyone can insert comments" ON comments
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update own comments" ON comments
    FOR UPDATE USING (auth.uid()::text = email);

-- 创建评论投票表
CREATE TABLE IF NOT EXISTS comment_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  ip_address INET NOT NULL,
  vote_type VARCHAR(10) NOT NULL CHECK (vote_type IN ('like', 'dislike')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(comment_id, ip_address)
);

-- 为投票表创建索引
CREATE INDEX IF NOT EXISTS idx_comment_votes_comment_id ON comment_votes(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_votes_ip_address ON comment_votes(ip_address);

-- RLS for comment_votes
ALTER TABLE comment_votes ENABLE ROW LEVEL SECURITY;

-- 删除已存在的投票策略
DROP POLICY IF EXISTS "Anyone can view comment votes" ON comment_votes;
DROP POLICY IF EXISTS "Anyone can insert comment votes" ON comment_votes;

-- 创建投票表策略
CREATE POLICY "Anyone can view comment votes" ON comment_votes FOR SELECT USING (true);
CREATE POLICY "Anyone can insert comment votes" ON comment_votes FOR INSERT WITH CHECK (true);
`

async function createTables() {
  try {
    console.log('🚀 开始创建数据表...')

    // 使用 RPC 执行 SQL (Supabase 需要使用 service role key 来执行 DDL)
    // 但是 anon key 可能无法执行 DDL，我们先尝试一下

    // 首先测试能否查询系统表来验证权限
    const { data: tables, error: tablesError } = await supabase
      .from('information_schema.tables')
      .select('table_name')
      .eq('table_schema', 'public')
      .eq('table_name', 'comments')

    console.log('检查 comments 表是否存在:', { tables, tablesError })

    if (tablesError && tablesError.code === 'PGRST205') {
      console.log('⚠️  anon key 无法执行系统查询，需要 service role key')
      console.log('请从 Supabase Dashboard 获取 service role key')
      return false
    }

    // 如果可以查询，尝试插入测试数据来验证表是否存在
    const { data: testInsert, error: testError } = await supabase
      .from('comments')
      .select('count', { count: 'exact', head: true })

    if (testError) {
      if (testError.code === 'PGRST205') {
        console.log('📋 comments 表不存在，需要在 Supabase Dashboard 中手动创建')
        console.log('请访问 https://supabase.com/dashboard/project/ptukqwqbpjzqpqzvlrle/sql')
        console.log('然后粘贴以下 SQL：')
        console.log('=' .repeat(50))
        console.log(createTablesSQL)
        console.log('=' .repeat(50))
      } else {
        console.log('❌ 测试失败:', testError)
      }
    } else {
      console.log('✅ comments 表已存在！当前评论数:', testInsert)
    }

  } catch (err) {
    console.error('❌ 创建表时出错:', err)
  }
}

createTables()